### ISSUE TITLE
Please update documentation about limitations with API

### ISSUE THREAD

**Issue by cdluv** [vtomanov/queue#1]
Hi - I really like your implementation for a simple persistent queue implementation using ESP32 flash memory.

I've just gone through your code (manually) so I could be wrong of course, but my observations/questions are:
- The maximum queue size is 32K (but can change if required)
- What's the max message size? 
- What's the max # messages allowed in the queue?  (appreciate this depends on the queue size, but let's assume there's a formula for this.... 
- When adding a message to the queue, and the queue is full, the queue behaves like a ring buffer - that is, the oldest message is lost, in order to make room for the newest message.

Please can you add these answers to the readme file?

Thanks!

**Comment by vtomanov** [comment]
Comments bellow Sent from my iPhoneOn 7 Mar 2023, at 23:47, Gary Fry ***@***.***> wrote:﻿
Hi - I really like your implementation for a simple persistent queue implementation using ESP32 flash memory.
I've just gone through your code (manually) so I could be wrong of course, but it looks like:

The maximum queue size is 32K (but can change if required) VT> this depends on the eeprom space user want to dedicate to the Q and is mentioned in the readme :#define EEPROM_Q_PARTITION_SIZE (32 * 1024)
messages can't me more than 127 bytes in length.VT> maximum message size is 255 bytes
No more than 255 messages can exist in the queue.VT> this depends on the table size that the user decide to dedicate - default table size is #define EEPROM_Q_BLOCK_SIZE (4 * 1024)1 element descriotion takes 16 bytes e.g fir 4kb table - max elements is 256 If you have bugger eeprom available you can increase the table size and host mire elements
When adding a message to the queue, and the queue is full, the queue behaves like a ring buffer - that is, the oldest message is lost, in order to make room for the newest message.VT> correct

Please can you add these features to the readme file?
Thanks!

**Comment by vtomanov** [comment]
Also thank you as looking at your suggestion I found a issue in case teh messages are too small and there is not space in the Q_TABLE the logic is wrong.

**Comment by vtomanov** [comment]
All updated - Thank you!

**Comment by vtomanov** [comment]
Reverted to original - as I got it wrong - the limit of elements is based  only of how much space there is the the data part -

only the comments for max element size <= 255 and overriding the oldest elements is added
